# Generated by Django 4.1.1 on 2022-09-17 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=165)),
                ('preco', models.CharField(max_length=16)),
                ('descrição', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Tatoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categoria')),
            ],
        ),
    ]
