# Generated by Django 4.1.1 on 2022-09-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tatoo_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatoo',
            name='imagem',
            field=models.ImageField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
