# Generated by Django 4.1.1 on 2022-09-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tatoo_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
